# Generated by Django 5.2 on 2025-04-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('ipv4_address', models.CharField(max_length=15)),
                ('ipv6_address', models.CharField(max_length=45)),
                ('action', models.TextField()),
                ('get_params', models.TextField()),
                ('post_params', models.TextField()),
            ],
        ),
    ]
